language: php

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick
  - cp .env.example .env
  - travis_retry composer install --no-interaction --no-suggest
  - php artisan key:generate
  - php artisan passport:keys

script:
  - vendor/bin/phpunit
