name: tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: imagick
          tools: composer:v2

      - uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing.example', '.env');"

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Generate key
        run: php artisan key:generate

      - name: Generate passport keys
        run: php artisan passport:keys

      - name: Start Websockets
        run: php artisan websockets:serve &

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test
